apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: worker
  name: worker
  namespace: zad1
spec:
  containers:
  - image: nginx
    name: worker
    resources: 
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 250m
        memory: 250Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
